use_frameworks!

target 'VersaPlayerAdsExtension_Example' do
  pod 'VersaPlayerAdsExtension', :path => '../'

  target 'VersaPlayerAdsExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'VersaPlayer'
    pod 'GoogleAds-IMA-iOS-SDK'
  end
end
